[project]
name = "compose-rules-docs"
version = "0.1.0"
description = "Documentation for Compose Rules"
requires-python = ">=3.10"
dependencies = [
    "mkdocs>=1.5.0",
    "mkdocs-material>=9.5.0",
    "mdx-truly-sane-lists>=1.3",
    "mike>=2.0.0",
]

