name: Preview documentation

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - 'pyproject.toml'

concurrency: preview-${{ github.ref }}

jobs:
  preview_docs:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      TERM: dumb

    steps:
      - uses: actions/checkout@v6

      - name: Setup uv
        if: github.event.action != 'closed'
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: uv sync --frozen

      - name: Build documentation
        if: github.event.action != 'closed'
        run: uv run mkdocs build

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
